#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw enable
sudo ufw allow "Nginx HTTP"
sudo ufw allow "OpenSSH"
sudo ufw enable
sudo ufw status
sudo ufw reload
sudo chown -R $USER:$USER /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
