#!/usr/bin/env bash
# Install nginx and start it
sudo apt-get update -y && sudo apt-get upgrade -y 
sudo apt-get -y install nginx

# Firewall setting: Allow Nginx to serve on HTTP
sudo ufw allow 'Nginx HTTP'

# Create a new index.html file that will be used over the default index.nginx-debian.html
sudo echo "Hello World!" >> /var/www/html/index.html

#Give the user  ownership to website files
sudo chown -R $USER:$USER /var/www/html
sudo sudo chmod -R 755 /var/www

# Redirect to /redirect_me to a youtube video
sed -i '37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Setup 404 page
sudo echo "Ceci n'est pas une page\n" >> /var/www/html/error_404.html
sudo sed -i '38i\error_page 404 /error_404.html;' /etc/nginx/sites-available/default

sudo service nginx start
sudo service nginx restart
sudo service nginx reload
