#!/usr/bin/env bash
# Installs MySQL server version 5.7.x
ssh ubuntu@34.204.199.6
ssh ubuntu@100.24.117.31
sudo apt-key add './mysql-5.7_signature.key'
sudo sh -c 'echo "deb http://repo.mysql.com/apt/ubuntu bionic mysql-5.7" >> /etc/apt/sources.list.d/mysql.list'
sudo apt-get update
sudo apt install -f mysql-client=5.7* mysql-community-server=5.7* mysql-server=5.7*
# password: ubuntu_user_pwd

-- Creates a user with a replication client privilege
CREATE USER IF NOT EXISTS 'holberton_user'@'localhost' IDENTIFIED BY 'projectcorrection280hbtn';
GRANT REPLICATION CLIENT ON *.* TO 'holberton_user'@'localhost';
FLUSH PRIVILEGES;
