#!/usr/bin/env bash
# Configures a ufw firwall to block all incoming traffic
#+ except for ports 22, 443 and 80
ssh ubuntu@34.204.199.6
apt update -y
apt-get install ufw -y
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
ufw disable
ufw enable
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
